### ISSUE TITLE
[SUGGESTION] Adding pre-commit hooks for linting/formatting the code

### ISSUE THREAD

**Issue by pzarabadip** [SMTG-UCL/surfaxe#10]
Hi,
Thanks for developing this nice package.  

While I was reading/reviwing the code, I found couple of unused imports/variables (listed below). I suggest adding `pre-commit` hooks with `pylint`, `yapf`, and `prospector` to format/lint code at commits. This would capture these and also improves readability of the code. 

**Unused imports**:
* `os`,`mpl`,`plt`, `Element`, `Lattice`, and `SiteCollection` in `analysis.py`.
* `Structure` and `numpy` in `convergence.py`.
* `os` in `generation.py`.
* `mpl` in `io.py`.
* `Slab`, `Element`, `PeriodicSite` in `vasp_data.py`.
* `warnings` and `Structure` in `test_analysis.py`.
* `warnings`, `os`, `Structure`, and `Slab` in `test_convergence.py`
* `warnings`, `Structure` in `test_generation.py`
* `warnings`, `os`, `Structure`, `surfaxe.io` in `test_io.py`

**Unused variables**:
* `files` [here](https://github.com/SMTG-UCL/surfaxe/blob/b3f5fe8a40b96d326e55dc51241b93c81ec75291/surfaxe/convergence.py#L90)
* `low` and `high` [here](https://github.com/SMTG-UCL/surfaxe/blob/b3f5fe8a40b96d326e55dc51241b93c81ec75291/surfaxe/vasp_data.py#L302)

Best regards,
Pezhman

**Comment by brlec** [comment]
Hi, 

Thank you for reviewing the code and flagging these! I have now removed the unused imports in the [latest commit](https://github.com/SMTG-UCL/surfaxe/commit/d21c74a76c561c08bf5297c51b7ba3d66d7c1b75) on `develop` - these will be merged with `master` once the JOSS review is complete. Regarding unused variables, `pylint` doesn't pick up on where  `low` and `high` are referenced later on in dataframe query, so they were left in. 

Best,
Kat
