### ISSUE TITLE
customise the number of parallel workers

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/surfaxe#14]
When parallelisation is used, the nubmer of the wokre is the same as the number of cpus. However, the cpus detected can be logical processor not physically cores. If a CPU has hyperthreading, then only half of the logical processors should be used. 

In general, it would be useful lower the number of workers. In addition, too many worker can lead to increased memory usage due to the overheads.

**Comment by brlec** [comment]
Again, very sorry this took me like a year to get to - I've this now to slab generation in [2ae49fb](https://github.com/SMTG-UCL/surfaxe/commit/2ae49fb320b2da43d8ccfa52ab1e86107bbe7e78) and to parse energies in [404f45e](https://github.com/SMTG-UCL/surfaxe/commit/404f45e85ed1d3eaef732bd8f937660ae92783f1) and limited the request to maximum available - 1 (from `multiprocessing.cpu_counts()`). 

I won't claim to understand the logical vs physical CPUs argument; nor do I have an opinion on multithreading vs multiprocessing but I reckon that'll do for surfaxe for now 🤠 it gives a decent speedup and it will work well enough for the average user, where the data sets will rarely go beyond 30-50 surfaces. If you think it's worth exploring more, we can discuss this more tho.
